[project]
name = "games-esphome"
version = "0.1.0"
description = "Game Runner for ESPHome"
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "ruff>=0.8.0",
    "clang-format>=19.0.0",
    "clang-tidy>=19.0.0",
]
